apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: testee
spec:
  clusterNetwork:
    services:
      cidrBlocks: [10.96.0.0/12]
    pods:
      cidrBlocks: [192.168.0.0/16]
    serviceDomain: cluster.local
  infrastructureRef:
    apiVersion: "cluster.weave.works/v1alpha3"
    kind: ExistingInfraCluster
    name: testee
---
apiVersion: cluster.weave.works/v1alpha3
kind: "ExistingInfraCluster"
metadata:
  name: testee
spec:
      user: root
      apiServer:
        extraArguments: []
      kubeletArguments: []
      os:
        files:
        - source:
            configmap: repo
            key: kubernetes.repo
          destination: /etc/yum.repos.d/kubernetes.repo
        - source:
            configmap: repo
            key: docker-ce.repo
          destination: /etc/yum.repos.d/docker-ce.repo
        - source:
            configmap: repo
            key: cloud-google-com.gpg.b64
          destination: /tmp/cloud-google-com.gpg.b64
        - source:
            configmap: docker
            key: daemon.json
          destination: /etc/docker/daemon.json
      cri:
        kind: docker
        package: docker-ce
        version: 19.03.8
