apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgBCGgAKUAmKJLG0lyx34Iox8ponTE20eLb7qijXCRdLp137HJbUT4QdztciWYcMsMu0Gvdj7tFHdPJHCvF5j5i4081IDHsUXEzPDIpDM3kJhR+DwaJZnsZzfXOLKlYY1JhC1RtF4/D9YGp5eBpejjE3yCOWDUSwAsU5MWfTQkEyPPtUpSg6XVOS1psfMD/A0PqJnWRl9AspmyCf/+SK+X9oMBYcdW03u6sqcn4xeUwokgQfkdTgBD0lq/jn+9C565Nl0UUQz3gHj9UbjshFeHVpaa0Q5NT0xH3RRhGXQxXJ7A3g1GcirzKsFvWVAMKTF2MtkdEDN0l+vSRZoWheBysqW5hz2M/1gejAW3H57TGa3FLGA+dO5/hfy/fG9S6bWeGI4+M9njuAtmlHpkBgaXnFDD40pAWmpcDo/1bXfzWE7FaQxgoLP1WXNrLCAgM6xVX/FmsIfXaw1u6GAlq8/uykvOO80d3eE2r0slaZgPCUHxfFbwkyzOZw1CyztT4+CJcIVSHkvzETEKAQLZvQKJUSGTxWhjQr8vybYitU6626USqG6yln2GcAeru0Z/ujXP2GyedHsGPvm54Q3dM1jtjjKjD5RWbM+QFDpsBVE3IHnzc7yvlYRTUbUCIFqxpSgKg52k/7XCpJzYjrDL785nZhciUNiCqwghVJeIogTKk8C3CCeaICqJM3KB2CVIF+C6/Vehd1NRxL4lqgHPuhHC8p
    username: AgAxju/bCVD1cmGJmQvJlkFsuoQUiVxl/a/covLL0iYpn/JGcXz7dl/9ZONfflEqFo7hHpdDz80VIm6geP6pLalkAOhvh8VjEZLvKHWHKu1ZanFHVWEXMBVqWbcxNt5gmdjN7BvjFHdKKR2fJCevAhei/wWe//VeSaFaZH/+E4KBA1Dbrc3DGvcszhJLS3qMiFKeMMsVeP062ZttB7vMbxDT3t6bbpAOaHXafnSYqlK/2vbC0qKIwEFZ/3inBJtueZqvK3V3l2Yg4GpxtgrXWxx3MiTmdMQ4eASX3+j9DJ9UIUnpgFzSaBnCUO9vQfz636uzBOLkNna7cgrGnVrnuRgf/QKe9JZmNdkC/vjODnNSr+dZyRjhVbTsDIwdicxr4rlWWE/oW0AqSSBxz7LX6WlrBTjV3o346hf2R6K7TRO9cXyxGZduo7QKJ07VUpz2BgrY8bherywfwg+qewTg+cm3Eej2j+SJOqwn2pBJ7cGDghO9zX+2odEYeUUCt5GDqiimnRfEvuAKeSW7N2G/LaN8SwewqeTICDUREcUvTq8OSDrC2xRcQEuhcfEHPVj1PpXr8L2VJBvDfevSUD3hTpfD7JU3Gqf8v2ky+ayTpbwlOvUnZouWVPnHs7dm9w+gmf2jlI0EB0XCdbgvUVfrp2Z0OCGK+ZgHMJwAnGfqMOsie4jqa5oxWizPRINF2j7wM+XXhbqeV42xcGs=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

